export const FAQs = [
  {
    title:
      "How can ReadmePro improve my GitHub profile to attract recruiters and boost my career?",
    description: (
      <>
        <p>
          ReadmePro significantly enhances your GitHub profile by generating{" "}
          <strong className="text-gray-800">
            clear, professional, and comprehensive documentation
          </strong>{" "}
          for your projects.
        </p>
        <p className="mt-4">
          As companies increasingly shift away from traditional technical
          interviews—such as coding exercises on platforms like LeetCode—your{" "}
          <strong className="text-gray-800">
            project portfolio has become more critical than ever
          </strong>{" "}
          .
        </p>
        <p className="mt-4">
          By using ReadmePro to document your projects, you clearly demonstrate
          your project&apos;s{" "}
          <strong className="text-gray-800">
            purpose, complexity, and value
          </strong>{" "}
          , making your GitHub portfolio stand out to recruiters and tech
          companies, greatly boosting your career prospects.
        </p>
      </>
    ),
  },
  {
    title:
      "How long does it take to generate a high-quality README with ReadmePro?",
    description: (
      <>
        <p className="">
          The time required to generate a high-quality README depends on the
          size and complexity of your codebase. ReadmePro&apos;s AI agent{" "}
          <strong className="text-gray-800">
            thoroughly reviews each file
          </strong>{" "}
          in your repository to gather essential details, ensuring that the
          resulting documentation accurately reflects your project&apos;s depth
          and functionality.
        </p>
        <p className="mt-4">
          Typically, the process takes{" "}
          <strong className="text-gray-800">
            only a few minutes, even for large projects
          </strong>
          , delivering professional documentation{" "}
          <strong className="text-gray-800">swiftly and efficiently</strong>.
        </p>
      </>
    ),
  },
  {
    title: "Is my code protected and secure when using ReadmePro?",
    description: (
      <>
        <p className="">
          <strong className="text-gray-800">Yes, absolutely</strong>. ReadmePro
          prioritizes the{" "}
          <strong className="text-gray-800">
            security and privacy of your code
          </strong>{" "}
          .
        </p>
        <p className="mt-4">
          We integrate directly with GitHub through a{" "}
          <strong className="text-gray-800">secure OAuth authentication</strong>
          , ensuring safe interactions with your repositories. We{" "}
          <strong className="text-gray-800">
            never store any of your code or data
          </strong>
          , and your codebase is{" "}
          <strong className="text-gray-800">
            never used to train our AI models
          </strong>{" "}
          .
        </p>
        <p className="mt-4">
          Your{" "}
          <strong className="text-gray-800">
            privacy and data security are guaranteed
          </strong>{" "}
          at all times.
        </p>
      </>
    ),
  },
  {
    title:
      "Can I customize the layout and style of my README generated by ReadmePro?",
    description: (
      <>
        <p className="">
          <strong className="text-gray-800">Yes!</strong> ReadmePro offers{" "}
          <strong className="text-gray-800">
            robust customization options
          </strong>{" "}
          to match your personal or project branding.
        </p>
        <p className="mt-4">
          You can easily add specialized sections such as{" "}
          <strong className="text-gray-800">
            feature highlights, contribution guidelines, project indexes, logos,
            and much more
          </strong>{" "}
          .
        </p>
        <p className="mt-4">
          Additionally, you have{" "}
          <strong className="text-gray-800">
            full control over text styling, alignment, and formatting
          </strong>
          , enabling you to create{" "}
          <strong className="text-gray-800">
            visually appealing, distinctive, and professional READMEs tailored
            exactly to your needs
          </strong>{" "}
          .
        </p>
      </>
    ),
  },
  {
    title: "Which programming languages does ReadmePro support?",
    description: (
      <>
        <p className="">
          ReadmePro supports{" "}
          <strong className="text-gray-800">ALL programming languages</strong>.
        </p>
        <p className="mt-4">
          Our advanced AI agent{" "}
          <strong className="text-gray-800">
            intelligently detects and comprehends every programming language
          </strong>{" "}
          , making it highly compatible not only with single-language projects
          but also complex multi-language codebases.
        </p>
        <p className="mt-4">
          <strong className="text-gray-800">Regardless of your stack</strong>,
          ReadmePro will generate{" "}
          <strong className="text-gray-800">
            accurate and professional documentation seamlessly
          </strong>{" "}
          .
        </p>
      </>
    ),
  },
  {
    title:
      "How does ReadmePro&apos;s AI analyze and review my code to create documentation?",
    description: (
      <>
        <p className="">
          ReadmePro utilizes a{" "}
          <strong className="text-gray-800">
            powerful AI agent specifically trained
          </strong>{" "}
          to systematically analyze your entire codebase.
        </p>
        <p className="mt-4">
          It carefully collects detailed information such as{" "}
          <strong className="text-gray-800">
            dependencies, libraries, individual file functionality, project
            structure, and entry points
          </strong>{" "}
          .
        </p>
        <p className="mt-4">
          All gathered insights are synthesized into{" "}
          <strong className="text-gray-800">
            clear, concise, and well-structured documentation
          </strong>
          , ensuring that your projects are represented{" "}
          <strong className="text-gray-800">
            professionally and accurately
          </strong>{" "}
          .
        </p>
      </>
    ),
  },
];
